---
- hosts: dev
  become: True
  tasks:
    - name: pip install
      apt:
        name: python3-pip
        state: present
    - name: Install docker-py module
      pip:
        name: docker-py
        state: present
    - name: start the docker container
      docker_container:
        name: sony
        image: "2222s/sony:$BUILD_NUMBER"
        state: started
        published_ports:
          - 0.0.0.0:82:8080 
